spring.application.name=shareway-backend
server.port=8080

#spring.profiles.active=dev
#spring.config.import=optional:configserver:http://localhost:8888


spring.datasource.url=jdbc:h2:mem:shareway_dev
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:h2.sql
