name: ShareWay
services:
  db:
    image: mariadb:11.3.2
    container_name: shareway-db
    environment:
      MYSQL_USER: 'shareway_user'
      MYSQL_PASSWORD: 'shareway_password'
      MYSQL_DATABASE: 'shareway'
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"